DROP DATABASE IF EXISTS DBXukaShop;
CREATE DATABASE DBXukaShop;
Use DBXukaShop;

CREATE TABLE NHANVIEN(
    MANV			VARCHAR(50),
    TENNV		NVARCHAR(50),
    DIACHI		NVARCHAR(50),
    NGAYSINH	VARCHAR(10),
    CHUCVU 	VARCHAR(50),
    LUONG		DECIMAL,
    
    CONSTRAINT NHAVIEN_MANV PRIMARY KEY (MANV)
);

CREATE TABLE LOAISP(
    MALOAISP		VARCHAR(50),
    TENLOAISP		NVARCHAR(50),
    
    CONSTRAINT LOAISP_MALOAISP PRIMARY KEY (MALOAISP)
);

CREATE TABLE SANPHAM(
    MASP		VARCHAR(50),
    TENSP		NVARCHAR(50),
    DONGIA		DECIMAL,
    MOTA		TEXT,
    TINHTRANG	TEXT,
    MALOAISP 	VARCHAR(50),
    
    CONSTRAINT SANPHAM_MASP PRIMARY KEY (MASP),
    CONSTRAINT SANPHAM_MALOAISP FOREIGN KEY(MALOAISP) REFERENCES LOAISP(MALOAISP)
);

CREATE TABLE LOAIKHUYENMAI(
    MALOAIKM		VARCHAR(50),
    TENLOAIKM		NVARCHAR(50),
    NGAYBATDAU			VARCHAR(50),
    NGAYKETTHUC			VARCHAR(10),
    TRIGIA	INT,
    
    CONSTRAINT LOAIKHUYENMAI_MALOAIKM PRIMARY KEY (MALOAIKM)
);

CREATE TABLE KHUYENMAI(
    MASPKM				VARCHAR(50),
    MALOAIKM			VARCHAR(50),
    TENKM				VARCHAR(50),
    MOTA					TEXT,
    CONSTRAINT SANPHAMKM_MASPKM PRIMARY KEY (MASPKM,MALOAIKM),
    CONSTRAINT SANPHAMKM_MALOAIKM FOREIGN KEY(MALOAIKM) REFERENCES LOAIKHUYENMAI(MALOAIKM),
    CONSTRAINT SANPHAMKM_MASPIKM FOREIGN KEY(MASPKM) REFERENCES SANPHAM(MASP)
);

CREATE TABLE KHACHHANG(
    MAKH		VARCHAR(50),
    TENKH		VARCHAR(50),
    EMAIL			VARCHAR(50),
    SODIENTHOAI			VARCHAR(10),
    MATKHAU	VARCHAR(50),
    DIACHI		VARCHAR(100),
    DIEMTICHLUY	INT,
    
    CONSTRAINT KHACHHANG_MAKH PRIMARY KEY (MAKH)
);
CREATE TABLE DONHANG(
    MADONHANG		VARCHAR(50),
    KHACHHANG			varchar(50),
    MASPKM				VARCHAR(50),
    TRANGTHAI		NVARCHAR(50),
    TINHTRANG	NVARCHAR(50),
    NGAYDAT			VARCHAR(10),
    TONGTIEN		DECIMAL,
    CACHTHANHTOAN			VARCHAR(50),
    
    CONSTRAINT DONHANG_MADONHANG PRIMARY KEY (MADONHANG),
	CONSTRAINT DONHANG_KHACHHANG FOREIGN KEY(KHACHHANG) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT DONHANG_MASPKM FOREIGN KEY(MASPKM) REFERENCES KHUYENMAI(MASPKM)
);

CREATE TABLE CHITIETDONHANG(
    MADONDAT	VARCHAR(50),
    MASP		VARCHAR(50),
    SOLUONG		INT,
    
    CONSTRAINT CHITIETDONHANG_MADONDAT PRIMARY KEY (MADONDAT, MASP),
    CONSTRAINT CHITIETDONHANG_MASP FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
    CONSTRAINT CHITIETDONHANG_MADON FOREIGN KEY(MADONDAT) REFERENCES DONHANG(MADONHANG)
);

CREATE TABLE QUIDINH(
    TUOITOITHIEU	INT,
    NGAYXULYTOIDA		INT,
    
    CONSTRAINT QUIDINH_KEY PRIMARY KEY (TUOITOITHIEU, NGAYXULYTOIDA)
);

